/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * User login
     * @description User login to get access token
     */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * User logout
     * @description User logout to invalidate token
     */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh token
     * @description Refresh access token with current token
     */
    post: operations['refreshToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    LoginReq: {
      username?: string
      password?: string
    }
    LoginVO: {
      token?: string
      user?: components['schemas']['UserVO']
    }
    UserVO: {
      /** Format: int64 */
      id?: number
      username?: string
      nickname?: string
      email?: string
      avatar?: string
    }
    ResultLoginVO: {
      /** Format: int32 */
      code?: number
      message?: string
      data?: components['schemas']['LoginVO']
    }
    ResultVoid: {
      /** Format: int32 */
      code?: number
      message?: string
    }
    ResultString: {
      /** Format: int32 */
      code?: number
      message?: string
      data?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginReq']
      }
    }
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResultLoginVO']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResultVoid']
        }
      }
    }
  }
  refreshToken: {
    parameters: {
      query?: never
      header?: {
        /** @description Authorization token */
        Authorization?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResultString']
        }
      }
    }
  }
}
